name: grimoire
description: "Web Novels & More"
publish_to: 'none'
version: 1.0.0+13

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:

  flutter:
    sdk: flutter

  add_2_calendar: ^3.0.1
#  animated_icon: ^0.0.9
#  animated_bottom_navigation_bar: ^1.3.3
  build_runner: ^2.4.11
  blur: ^4.0.0

  cached_network_image: ^3.4.1
  cloud_firestore: ^5.4.2
  custom_image_crop: ^0.0.13


#  carousel_slider: ^5.0.0
#  chat_bubbles: ^1.5.0
#  color_mesh: ^0.0.7
#
#
  connectivity_plus: ^6.1.0
  clipboard: ^0.1.3


#  animated_box_decoration: ^0.0.7
  external_path: ^2.0.1
  free_english_dictionary: ^0.0.3
  double_back_to_close_app: ^2.1.0

  device_info_plus: ^10.1.2
  date_time_format: ^2.0.1
  easy_url_launcher: ^0.0.6
  enefty_icons: ^1.0.7

  firebase_core: ^3.5.0
  # flutter_localization: ^0.2.2
  firebase_pagination: any
  flutter_markdown: ^0.7.4+1
  fluttertoast: ^8.2.8

  flutter_image_slideshow: ^0.1.6
  flutter_svg_provider: ^1.0.7

  flutter_masonry_view: any
  firebase_auth: ^5.3.0
  firebase_storage: any
  flutter_launcher_icons: ^0.13.0
  # flutter_translate: ^4.0.4
  flutter_native_splash: ^2.4.2
  flutter_localizations:
    sdk: flutter

  flutter_p2p_connection: ^1.0.3 # // send books offline
#  flutter_pdfview: ^1.3.3
#  flutter_downloader: ^1.11.8
  filesystem_picker: ^4.1.0
#  thumbnailer: ^2.2.0
  google_sign_in: ^6.2.1
  google_fonts: ^6.2.1
  google_mobile_ads: ^2.0.0 # ^5.2.0
  intl: any

  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
#  magic_text: ^0.0.3
#  file_previewer: ^0.2.0
  file_picker: ^8.1.3
  flutter_tts: ^3.8.3
#  flutter_ad_manager_web: ^0.0.1
  go_router: ^14.3.0


  hive: ^2.2.3
  hive_flutter: ^1.1.0


  image_picker: ^1.1.2
  in_app_purchase: ^3.2.0
  is_first_run: ^1.0.0

  markdown_widget: ^2.3.2+6
  markdown_editor_plus: ^0.2.15

  # numhelpers: ^1.0.0
#  flutter_media_metadata: ^1.0.0+1
#  picture_cropper: ^0.1.15

#  in_app_purchase: ^3.2.0
#  flutter_pdf_text: ^0.7.0
  timer_stop_watch: ^1.0.0
#  google_mlkit_translation: ^0.12.0

  keep_screen_on: ^3.0.0

  language_picker: ^0.4.5
  line_icons: ^2.0.3
  launch_app_store: ^1.1.2

  provider: ^6.1.2
#  pdfrx: ^1.0.84
  playx_version_update: ^0.0.7
  permission_handler: ^10.4.5
  path: ^1.9.0
  pdf_thumbnail: ^0.1.6+1
  path_provider: ^2.1.5

  read_pdf_text: ^0.2.2
  remove_markdown: ^0.0.2
#  realtime_pagination: ^0.0.8

  shared_preferences: ^2.3.2
  social_sharing_plus: ^1.2.3
  share_plus: ^10.1.2
  store_redirect: ^2.0.3
#  syncfusion_flutter_pdfviewer: ^27.1.57
  stop_watch_timer: ^3.2.1
  svgator_player_flutter: ^2.0.0

  typesense: ^0.5.1
  rate_us_on_store: ^0.0.3
  url_strategy: ^0.3.0
  uuid: ^4.5.1

#  easy_pdf_viewer: ^1.0.8
#  pdfx: ^2.6.0
#  get: ^4.6.5

  visibility_detector: ^0.4.0+2
  # flutter_gen: ^5.8.0
#  inview_notifier_list: ^3.0.0







dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    # Add assets from the images directory to the application.
#    - assets/google2.png
    - assets/i18n/

    - assets/icon.png
    - assets/empty.png
#    - assets/no_internet.png
#    - assets/google2.png
    - assets/splash.png
#    - assets/wip.png
    - assets/book_cover.png
#    - assets/image1.svg
    - assets/image2.svg
#    - assets/image3.svg
    - assets/image4.svg
    - assets/image5.svg
    - assets/image6.svg
#    - assets/image7.svg
    - assets/image8.svg


flutter_launcher_icons:
  # launchwith ---  dart run flutter_launcher_icons:main
  image_path: "assets/icon.png"
  android: true



flutter_native_splash:
  # launchwith --- dart run flutter_native_splash:create
  color: "#000000"
  image: assets/splash.png
  android: true
  ios: true
  web: true
  fullscreen: true





   # dart run flutter_native_splash:create  \  dart run flutter_launcher_icons:main \ flutter run -d emulator-5554 -v