name: grimoire
description: "PDF Reader"
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:

  flutter:
    sdk: flutter
  animated_bottom_navigation_bar: ^1.3.3
  build_runner: ^2.4.11

  cached_network_image: ^3.4.1
  cloud_firestore: ^5.4.2

  carousel_slider: ^5.0.0
#  connectivity_plus: ^6.1.0


  external_path: ^2.0.1
  double_back_to_close_app: ^2.1.0

  device_info_plus: ^9.1.2
  easy_url_launcher: ^0.0.7
  enefty_icons: ^1.0.7

  firebase_core: ^3.5.0
  firebase_pagination: any

  flutter_masonry_view: any
  firebase_auth: ^5.3.0
  firebase_storage: any
  flutter_launcher_icons: ^0.14.0
  flutter_p2p_connection: ^1.0.3 # // send books offline
  flutter_pdfview: ^1.3.3
#  flutter_downloader: ^1.11.8
  filesystem_picker: ^4.1.0
  thumbnailer: ^2.2.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1

  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  google_mobile_ads: ^5.2.0
  file_previewer: ^0.2.0
  file_picker: ^8.1.3

  image_picker: ^0.8.9

#  in_app_purchase: ^3.2.0

  provider: ^6.1.2
#  playx_version_update: ^0.0.7
  permission_handler: ^10.4.5
  path: ^1.9.0
  pdf_thumbnail: ^0.1.6+1
#  realtime_pagination: ^0.0.8

  shared_preferences: ^2.3.2

  syncfusion_flutter_pdfviewer: ^26.1.41
  rate_us_on_store: ^0.0.3
  url_strategy: ^0.3.0
  uuid: ^4.5.1
  flutter_native_splash: ^2.4.2






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    # Add assets from the images directory to the application.
#    - assets/google2.png
    - assets/icon.png
    - assets/empty.png
    - assets/no_internet.png
    - assets/google2.png
    - assets/pdf_image.png
    - assets/splash.png


flutter_launcher_icons:
  # launchwith ---  dart run flutter_launcher_icons
  image_path: "assets/icon.png"
  android: true
  web:
    generate: true
    image_path: "assets/icon.png"
  ios: true
  remove_alpha_ios: true


flutter_native_splash:
  # launchwith --- dart run flutter_native_splash:create
  color: "#000000"
  image: assets/splash.png
  android: true
  ios: true